// File generated by FlutterFire CLI.
// ignore_for_file: lines_longer_than_80_chars, avoid_classes_with_only_static_members
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for windows - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyCU9h-xsm3UX8KR8JxidSZy26Oh2pftlVY',
    appId: '1:249220792222:web:c44e71633838f15685e08f',
    messagingSenderId: '249220792222',
    projectId: 'f79firebase',
    authDomain: 'f79firebase.firebaseapp.com',
    storageBucket: 'f79firebase.appspot.com',
    measurementId: 'G-3ZDM5LDFKL',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyBMVwAfoC-tAAP-A4P1g4I99I85W4eHt9c',
    appId: '1:249220792222:android:9729f678a21db43f85e08f',
    messagingSenderId: '249220792222',
    projectId: 'f79firebase',
    storageBucket: 'f79firebase.appspot.com',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyDd7fPAG7hP0RGc1XC01Bu-VbQSnBxDqgQ',
    appId: '1:249220792222:ios:394ebad7e896e82685e08f',
    messagingSenderId: '249220792222',
    projectId: 'f79firebase',
    storageBucket: 'f79firebase.appspot.com',
    iosClientId: '249220792222-901gqqf7t1l37m0blvtv4tthc2kpa30i.apps.googleusercontent.com',
    iosBundleId: 'com.example.f79',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyDd7fPAG7hP0RGc1XC01Bu-VbQSnBxDqgQ',
    appId: '1:249220792222:ios:d47e8de4f5fba0c185e08f',
    messagingSenderId: '249220792222',
    projectId: 'f79firebase',
    storageBucket: 'f79firebase.appspot.com',
    iosClientId: '249220792222-jvg5q2pnlvkuc8gbmiiil9stsvhq34jp.apps.googleusercontent.com',
    iosBundleId: 'com.example.f79.RunnerTests',
  );
}
